from flask import jsonify
... 
... def role_required(roles):
... 
...     def decorator(func):
... 
...         def wrapper(current_user, *args, **kwargs):
... 
...             if current_user["role"] not in roles:
... 
...                 return jsonify({
...                     "message": "Access Denied"
...                 }), 403
... 
...             return func(
...                 current_user,
...                 *args,
...                 **kwargs
...             )
... 
...         wrapper.__name__ = func.__name__
... 
...         return wrapper
... 
